# Generated by Buildr 1.4.7, change to your liking


# Version number for this release
VERSION_NUMBER = "1.0.0"
# Group identifier for your projects
GROUP = "WSN-Clone-Detection"
COPYRIGHT = ""

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://repo1.maven.org/maven2"

desc "The Wsn-clone-detection project"
define "WSN-Clone-Detection" do

  project.version = VERSION_NUMBER
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT

  define "client" do
    compile.with # Add classpath dependencies
    package(:jar)
  end

  define "server" do
    compile.with # Add classpath dependencies
    package(:jar)
  end

end
